# Hook library name
LIBHOOK = libkea-flex-id.so

# Source code directory
SOURCE_DIR = .

KEA_INSTALLPREFIX = /usr
KEA_INC = /usr/include/kea
#KEA_INC = /usr/src/kea/src
KEA_INSTALLHOOKS = /usr/lib64/kea/hooks
# Build directory
BUILD_DIR = ./build

# List of all source files
SOURCE_FILES = $(wildcard $(SOURCE_DIR)/*.cc)

# List of object files
OBJECTS = $(patsubst $(SOURCE_DIR)/%.cc, $(BUILD_DIR)/%.o, $(SOURCE_FILES))

# Any special libraries (needed for build)
LIBS = \
	-lkea-dhcpsrv \
	-lkea-dhcp++ \
	-lkea-hooks \
	-lkea-log \
	-lkea-util \
	-lkea-exceptions

# Set the compiler
CPP = g++

# Set extra compiler flags
#CPPFLAGS = -Wall -Wextra -O2 -pedantic
CPPFLAGS = -Wall -Wextra -O2 -I$(KEA_INC) -I$(SOURCE_DIR)
